---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: flexmoney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rohanjoshi95/frontendapp:latest
          ports:
            - containerPort: 4200
              protocol: TCP
          resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: flexmoney
spec:
  type: LoadBalancer
  ports:
  - port: 4200
    targetPort: 4200
    protocol: TCP
  selector:
    app: frontend